### ISSUE TITLE
need an API URL for the SoDOFF main server

### ISSUE THREAD

**Issue by joeyjumper94** [SoDOff-Project/dragonrescue#1]

**Comment by hictooth** [comment]
This could change in the future, but at the moment its `https://api.sodoff.spirtix.com/`

**Comment by joeyjumper94** [comment]
could you put that info into the readme?

**Comment by hictooth** [comment]
Would prefer not to - there's a distinction between "the SoDOff software" and "the SoDOff hosted server". dragonrescue can be used with the SoDOff software, not just the specific hosted server. The hosted server help can be found on our discord.
